main: nl.dgoossens.autocraft.AutomatedCrafting
name: AutomatedCrafting
version: 1.12/1.14-2.2.2
description: An open-source autocrafting plugin for spigot.
load: STARTUP
author: Aeltumn
loadbefore: []
softdepend: [CustomCrafting]
api-version: 1.13
commands:
  reloadrecipes:
    permission: automatedcrafting.reload
    description: Reloads all recipes for the autocrafters, gets ran automatically when running /reload!
permissions:
  automatedcrafting.reload:
    default: op
    description: Allows you to use /reloadrecipes.
  automatedcrafting.makeautocrafters:
    default: true
    description: Allows users to make autocrafters.