main: nl.dgoossens.autocraft.AutomatedCrafting
name: AutomatedCrafting
version: 1.0
description: An open-source autocrafting plugin for spigot.
load: STARTUP
author: Daniël Goossens
website: https://dgoossens.nl/
loadbefore: []
commands:
permissions:
api-version: 1.13