main: nl.dgoossens.autocraft.AutomatedCrafting
name: AutomatedCrafting
version: 1.12/1.14-2.0
description: An open-source autocrafting plugin for spigot.
load: STARTUP
author: Daniël Goossens
website: https://dgoossens.nl/
loadbefore: []
api-version: 1.13
commands:
  reloadrecipes:
    permission: automatedcrafting.reload
    description: Reloads all recipes for the autocrafters, gets ran automatically when running /reload!
permissions:
  automatedcrafting.reload:
    default: op
    description: Allows you to use /reloadrecipes.